name: frontend
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  email_validator: ^3.0.0
  google_sign_in: ^6.2.2
  font_awesome_flutter: ^10.1.0
  flutter_facebook_auth: ^7.1.1
  http: ^1.3.0
  flutter_riverpod: ^2.6.1
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  google_maps_flutter: ^2.0.6
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  provider: any
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  image: ^4.1.3
  file_picker: ^9.0.2
  socket_io_client: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/no_tasks.png

