name: frontend
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  email_validator: ^2.0.2
  google_sign_in: ^5.0.7
  font_awesome_flutter: ^10.1.0
  flutter_facebook_auth: ^5.0.0
  http: ^0.13.3
  flutter_riverpod: ^1.0.0
  geocoding: ^2.0.0
  geolocator: ^10.0.0
  google_maps_flutter: ^2.0.6
  cupertino_icons: ^1.0.8
  intl: ^0.17.0
  provider: any
  google_fonts: ^4.0.4
  image_picker: ^0.8.7+4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

